name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish ism7mqtt Windows
      run: dotnet publish -c release -r win-x64 --sc src/ism7mqtt/ism7mqtt.csproj
    - name: Publish ism7mqtt Linux
      run: dotnet publish -c release -r linux-x64 --sc src/ism7mqtt/ism7mqtt.csproj
    - name: Publish ism7mqtt Linux ARM
      run: dotnet publish -c release -r linux-arm --sc src/ism7mqtt/ism7mqtt.csproj
    - name: Publish ism7mqtt Linux ARM64
      run: dotnet publish -c release -r linux-arm64 --sc src/ism7mqtt/ism7mqtt.csproj
    - name: Publish ism7proxy Windows
      run: dotnet publish -c release -r win-x64 --sc src/ism7proxy/ism7proxy.csproj
    - name: Publish ism7proxy Linux
      run: dotnet publish -c release -r linux-x64 --sc src/ism7proxy/ism7proxy.csproj
    - name: Publish ism7proxy Linux ARM
      run: dotnet publish -c release -r linux-arm --sc src/ism7proxy/ism7proxy.csproj
    - name: Publish ism7proxy Linux ARM64
      run: dotnet publish -c release -r linux-arm64 --sc src/ism7proxy/ism7proxy.csproj
    - name: Publish ism7config Windows
      run: dotnet publish -c release -r win-x64 --sc src/ism7config/ism7config.csproj
    - name: Publish ism7config Linux
      run: dotnet publish -c release -r linux-x64 --sc src/ism7config/ism7config.csproj
    - name: Publish ism7config Linux ARM
      run: dotnet publish -c release -r linux-arm --sc src/ism7config/ism7config.csproj
    - name: Publish ism7config Linux ARM64
      run: dotnet publish -c release -r linux-arm64 --sc src/ism7config/ism7config.csproj
    - uses: actions/upload-artifact@v4
      with:
        name: ism7mqtt-win-x64
        path: src/ism7mqtt/bin/release/net10.0/win-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7mqtt-linux-x64
        path: src/ism7mqtt/bin/release/net10.0/linux-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7mqtt-linux-arm
        path: src/ism7mqtt/bin/release/net10.0/linux-arm/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7mqtt-linux-arm64
        path: src/ism7mqtt/bin/release/net10.0/linux-arm64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7proxy-win-x64
        path: src/ism7proxy/bin/release/net10.0/win-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7proxy-linux-x64
        path: src/ism7proxy/bin/release/net10.0/linux-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7proxy-linux-arm
        path: src/ism7proxy/bin/release/net10.0/linux-arm/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7proxy-linux-arm64
        path: src/ism7proxy/bin/release/net10.0/linux-arm64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7config-win-x64
        path: src/ism7config/bin/release/net10.0/win-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7config-linux-x64
        path: src/ism7config/bin/release/net10.0/linux-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7config-linux-arm
        path: src/ism7config/bin/release/net10.0/linux-arm/publish
    - uses: actions/upload-artifact@v4
      with:
        name: ism7config-linux-arm64
        path: src/ism7config/bin/release/net10.0/linux-arm64/publish